ADDED: Nueral Networks and Deep Learning
ishandeveloper/Coursify-hacktoberfest pull request #6
Opened 2020-10-01 11:52 UTC by kchatr

Added a course for machine learning for Issue #3

2020-10-01 11:54 UTC, ishandeveloper commented on courses/data.js
> +    tages: ["machine learning", "ai", "deep learning", "neural networks"]
Please fix this typo `tages`, and write `tags` instead.

2020-10-01 11:55 UTC, ishandeveloper requested changes
Please take a look at the comments I've made and resolve those issues.

2020-10-01 11:57 UTC, kchatr reviewed
Corrected the typo and added comma to the end for future contributors.

2020-10-01 12:00 UTC, merged

2020-10-01 12:01 UTC, ishandeveloper commented
Congrats on submitting your first PR! 🎊
Your changes have been merged and should be reflected on the website in a few minutes. 

### Happy hacking!

2020-10-01 13:20 UTC, kchatr commented
Thank you @ishandeveloper!! It's actually my first ever Hacktoberfest contribution :D.

2020-10-02 21:09 UTC, ishandeveloper commented
Hey @kchatr ! Just came back to see, I forgot to properly greet you on your first-time contribution towards an open-source project. :) 

Thank you for giving this repository the opportunity to help you guide in your first contribution. On behalf of everyone here, I'd like to say, 

### Welcome to the open-source community!
Have fun hacking!